# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='Quote', max_length=100),
            preserve_default=False,
        ),
    ]
