# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-22 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='author',
            field=models.CharField(default='fave', max_length=100),
            preserve_default=False,
        ),
    ]
